name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest

      - name: Configure and Build
        run: |
          cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DOULY_BUILD_TESTS=ON -DOULY_TEST_COVERAGE=ON
          cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
        shell: bash
        env:
          CC: gcc-14
          CXX: g++-14        
          
      - name: Test
        working-directory: ${{ github.workspace }}/build/unit_tests
        run: ctest -C ${{ env.BUILD_TYPE }}
      
      # Generate LCOV report (assumes coverage data was generated during tests)
      - name: Generate LCOV Coverage Report
        working-directory: ${{ github.workspace }}/build/unit_tests
        run: |
          # Capture coverage data from the build directory into a file named coverage.info
          lcov --capture --directory ${{github.workspace}}/include --directory ${{github.workspace}}/src -d . --no-external --output-file coverage.info
      
      # Upload the generated coverage report to Coveralls.io
      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: build/unit_test/coverage.info
